name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate with GCP
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Step 3: Configure GCP Project
    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Build Docker Image
    - name: Build Docker Image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-ci-cd-app:latest .

    # Step 5: Push Docker Image to GCR
    - name: Push Docker Image to GCR
      run: |
        gcloud auth configure-docker
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-ci-cd-app:latest

    # Step 6: Deploy to GKE
    - name: Deploy to Kubernetes
      run: |
        gcloud container clusters get-credentials YOUR_CLUSTER_NAME --zone YOUR_ZONE
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
